### ISSUE TITLE
Permettre l'installation avec composer

### ISSUE THREAD

**Issue by jducro** [Keyyo/keyyo-manager-php-client#1]
Afin de s'intégrer plus facilement dans une application PHP moderne, il faudrait fournir un fichier composer.json pour l'installation de la librairie.

Merci

**Comment by jtouati-keyyo** [comment]
Tu as tout à fait raison, et c'est prévu. Nous n'avons simplement pas eu le temps de mettre ça en place pour l'instant. Merci pour ta proposition de composer.json, on va s'en occuper ASAP.

**Comment by jtouati-keyyo** [comment]
C'est (enfin) en place !
